### ISSUE TITLE
MIT 라이센스의 경우 저작권 표시가 있는 한 Fork없이 복제가 가능합니다.

### ISSUE THREAD

**Issue by yechankun** [DarkTornado/BasicKbot#1]
MIT 라이센스 자체가 저작권을 표시하는 한 누구나 무료로 저장, 복제, 수정, 상업적이용이 가능하기 때문에 무언가 조치를 내릴 필요는 없습니다.
README.md 에 말씀하신 훔쳐갔다는 표현은 적확한 표현이 아닙니다.
오랜기간 개발을 하셔서 누군가 코드를 훔쳐간 것에 괘씸함이 느껴지실 수 있겠지만 MIT 라이센스인 이상 어쩔 수 없어 보입니다.

**Comment by DarkTornado** [comment]
제가 작성한 서적(.pdf 파일)까지 MIT 라이선스를 적용한 적은 없으며, Fork 기능을 사용하지 않으셨던 분은 무단 전재 및 복제 판매 등의 행위를 금지한다고 명시해둔 해당 파일까지 함께 배포중입니다.

**Comment by yechankun** [comment]
> 제가 작성한 서적(.pdf 파일)까지 MIT 라이선스를 적용한 적은 없으며, Fork 기능을 사용하지 않으셨던 분은 무단 전재 및 복제 판매 등의 행위를 금지한다고 명시해둔 해당 파일까지 함께 배포중입니다.

그건 많이 어지럽네요..
고생이 많으십니다 ㅠㅠ 😢

**Comment by DarkTornado** [comment]
추가적으로 당시 확인했을 당시 그 분의 Repository 177개 중 95개가 Fork 기능을 사용하지 않고 다운로드 후 본인 계정에 다시 업로드 하는 방식이었어요.
95개 중 11개는 원래 Repository가 어디에 있었는지 명시하지 않으셨구요.
다른 Repository를 Fork하신 적이 있는 것을 보면 Fork 기능이 있다는걸 모르시는 것은 아닌 듯 한데 :(
